version: 2
registries:
  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    username: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_USERNAME}}"
    password: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_PASSWORD}}"
  npm-registry-pkgs-dev-azure-com-juntossomosmais-packaging-portal:
    type: npm-registry
    url: https://pkgs.dev.azure.com/juntossomosmais/_packaging/Portals/npm/registry/:_password
    token: "${{secrets.NPM_REGISTRY_PKGS_DEV_AZURE_COM_JUNTOSSOMOSMAIS_PACKAGING_PORTAL_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@storybook/addon-knobs"
    versions:
    - ">= 6.a, < 7"
  - dependency-name: "@storybook/addons"
    versions:
    - ">= 6.a, < 7"
  - dependency-name: "@types/jest"
    versions:
    - ">= 26.a, < 27"
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.13.0
  - dependency-name: uniqid
    versions:
    - 5.3.0
  - dependency-name: "@testing-library/vue"
    versions:
    - 5.6.1
  - dependency-name: react-imask
    versions:
    - 6.0.5
    - 6.0.7
  - dependency-name: react-scripts
    versions:
    - 4.0.1
  - dependency-name: react-is
    versions:
    - 17.0.1
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.15
  registries:
  - npm-registry-npm-pkg-github-com
  - npm-registry-pkgs-dev-azure-com-juntossomosmais-packaging-portal
  - npm-registry-pkgs-dev-azure-com-juntossomosmais-packaging-portal
- package-ecosystem: npm
  directory: "/packages/core"
  schedule:
    interval: monthly
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@storybook/addon-a11y"
    versions:
    - ">= 6.a, < 7"
  - dependency-name: "@storybook/addon-knobs"
    versions:
    - ">= 6.a, < 7"
  - dependency-name: storybook-addon-themes
    versions:
    - ">= 6.a, < 7"
  - dependency-name: "@storybook/addon-viewport"
    versions:
    - ">= 6.a, < 7"
  - dependency-name: "@storybook/addon-docs"
    versions:
    - 6.1.20
  - dependency-name: "@storybook/addons"
    versions:
    - 6.1.20
  registries:
  - npm-registry-npm-pkg-github-com
  - npm-registry-pkgs-dev-azure-com-juntossomosmais-packaging-portal
  - npm-registry-pkgs-dev-azure-com-juntossomosmais-packaging-portal
- package-ecosystem: npm
  directory: "/packages/react-ds"
  schedule:
    interval: monthly
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: autoprefixer
    versions:
    - ">= 10.0.a, < 10.1"
  - dependency-name: "@storybook/react"
    versions:
    - ">= 6.a, < 7"
  - dependency-name: "@types/react"
    versions:
    - ">= 17.a, < 18"
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.1
  - dependency-name: rollup-plugin-typescript2
    versions:
    - 0.30.0
  - dependency-name: react-imask
    versions:
    - 6.0.7
  - dependency-name: autoprefixer
    versions:
    - 10.2.4
  registries:
  - npm-registry-npm-pkg-github-com
  - npm-registry-pkgs-dev-azure-com-juntossomosmais-packaging-portal
  - npm-registry-pkgs-dev-azure-com-juntossomosmais-packaging-portal
- package-ecosystem: npm
  directory: "/packages/styles"
  schedule:
    interval: monthly
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sass-loader
    versions:
    - ">= 11.a, < 12"
  registries:
  - npm-registry-npm-pkg-github-com
  - npm-registry-pkgs-dev-azure-com-juntossomosmais-packaging-portal
  - npm-registry-pkgs-dev-azure-com-juntossomosmais-packaging-portal
- package-ecosystem: npm
  directory: "/packages/venice-types"
  schedule:
    interval: monthly
    time: "08:00"
  open-pull-requests-limit: 10
  registries:
  - npm-registry-npm-pkg-github-com
  - npm-registry-pkgs-dev-azure-com-juntossomosmais-packaging-portal
  - npm-registry-pkgs-dev-azure-com-juntossomosmais-packaging-portal
- package-ecosystem: npm
  directory: "/packages/vue-ds"
  schedule:
    interval: monthly
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@storybook/vue"
    versions:
    - ">= 6.a, < 7"
  - dependency-name: "@vue/test-utils"
    versions:
    - 1.1.3
  registries:
  - npm-registry-npm-pkg-github-com
  - npm-registry-pkgs-dev-azure-com-juntossomosmais-packaging-portal
  - npm-registry-pkgs-dev-azure-com-juntossomosmais-packaging-portal
