export const colors = {
  '--color-neutral-dark-1': '#000',
  '--color-neutral-regular': '#1F2328',
  '--color-neutral-light-1': '#464F59',
  '--color-neutral-light-2': '#7E8B97',
  '--color-neutral-light-3': '#B9BFC6',
  '--color-neutral-light-4': '#DEE1E4',
  '--color-neutral-light-5': '#F1F3F3',
  '--color-neutral-white': '#fff',
  '--color-brand-primary-dark-1': '#b85000',
  '--color-brand-primary-regular': '#ed6700',
  '--color-brand-primary-light-1': '#ff913d',
  '--color-brand-primary-light-2': '#fff3eb',
  '--color-brand-secondary-dark-1': '#12579b',
  '--color-brand-secondary-regular': '#1976d2',
  '--color-brand-secondary-light-1': '#4a9ef2',
  '--color-brand-secondary-light-2': '#e4f0fc',
  '--color-contextual-error-dark-1': '#b60000',
  '--color-contextual-error-regular': '#d60000',
  '--color-contextual-error-light-1': '#ff0a0a',
  '--color-contextual-error-light-2': '#ffebeb',
  '--color-contextual-success-dark-1': '#106105',
  '--color-contextual-success-regular': '#168806',
  '--color-contextual-success-light-1': '#26b413',
  '--color-contextual-success-light-2': '#e4ffe0',
  '--color-contextual-warning-dark-1': '#856900',
  '--color-contextual-warning-regular': '#ffc900',
  '--color-contextual-warning-light-1': '#ffda52',
  '--color-contextual-warning-light-2': '#fff4cc',
}

export const spaceAliases = {
  '--spacing-xxsmall': 4,
  '--spacing-xsmall': 8,
  '--spacing-small': 12,
  '--spacing-base': 16,
  '--spacing-medium': 20,
  '--spacing-large': 24,
  '--spacing-xlarge': 28,
  '--spacing-xxlarge': 32,
  '--spacing-xxxlarge': 40,
  '--spacing-xxxxlarge': 48,
  '--spacing-giant': 64,
  '--spacing-xgiant': 80,
}

export const zIndexes = {
  '--border-radius': 4,
  '--zindex-1': 1,
  '--zindex-5': 5,
  '--zindex-10': 10,
  '--zindex-100': 100,
  '--zindex-1000': 1000,
  '--zindex-overlay': 10000,
  '--transition-duration': 0.25,
}

export const fonts = {
  '--font-family': 'Roboto, sans-serif',
  '--font-weight-regular': 400,
  '--font-weight-bold:': 700,
  '--font-weight-medium': 500,
}
